---
title: monigold.com
timezone: UTC
collections:
  _drafts:
    title: Drafts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: The website of Greg Monigold
author: Greg Monigold
baseurl: "/"
url: https://gregmonigold.github.io
twitter_username: 
github_username: 
facebook_username: 
linkedin_username: 
google_analytics: UA-XXXXXXXXX-X
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
